msg='This is a python course'
print(len(msg))
msg=msg.upper()
print(msg)
msg=msg.lower()
print(msg)
msg=msg.title()
print(msg)
msg=msg.replace('Python','Python 3.3')
print(msg)
print(msg.find('Python'))
print('course' in msg)